apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: presenter
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: presenter
    spec:
      containers:
      - image: deckhub/presenter:1.0.0-alpha2
        imagePullPolicy: Always
        name: presenter
        env:
          - name: Runtime__PathBase
            value: '/presenter'
          - name: Redis__Host
            value: 'redis'
          - name: AppMetrics__InfluxDbServer
            value: 'http://rlmetrics.eastus.cloudapp.azure.com:8086'
          - name: AppMetrics__InfluxDbDatabase
            value: 'deckhub'
          - name: Security__ApiKeyHashPhrase
            valueFrom:
              secretKeyRef:
                name: api-key
                key: hashPhrase
          - name: Messaging__ServiceBusConnectionString
            valueFrom:
              secretKeyRef:
                name: servicebus
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: presenter
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: presenter
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: presenter
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /presenter
        backend:
          serviceName: presenter
          servicePort: 80